language: python

cache:
  pip: true
  timeout: 1000

sudo: false

python:
- '2.7'
- '3.5'
- '3.6'
- '3.7'

os:
- linux

matrix:
  fast_finish: true
  allow_failures:
    - python: '2.7'

notifications:
  email: false

# repo branches to test
branches:
  only:
  - /.*/

before_install:
  - sudo apt-get update -y
  - sudo apt-get install -y lmod

install:
- git config remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
- git fetch --unshallow --tags
- pip install -U pip wheel --quiet
- pip install --upgrade setuptools --quiet
- pip install -r requirements.txt --quiet
- pip install pytest
- pip install pytest-coverage
- pip install coveralls
#- python setup.py install 

script:
- pytest --public-svn-only python/sdss_install/tests --cov python/sdss_install --cov-report html

after_success:
- coveralls
